services:
  db:
    image: postgres:14
    container_name: my-postgres
    restart: always
    environment:
      POSTGRES_USER: its
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_database
    ports:
      - "5432:5432"
    networks:
      - pgnetwork
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: my-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: mmishapet@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - pgnetwork
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - pgnetwork

  eureka-server:
    build:
      context: ./eureka-server
    container_name: eureka-server
    networks:
      - pgnetwork
    ports:
      - "8762:8762"

  booking-service:
    build:
      context: ./booking
    container_name: booking
    networks:
      - pgnetwork
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8762/eureka/
    ports:
      - "8001:8001"
    depends_on:
      - eureka-server
      - rabbitmq

  notification-service:
    build:
      context: ./notification
    container_name: notification
    networks:
      - pgnetwork
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8762/eureka/
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - rabbitmq


volumes:
  postgres_data:
  pgadmin_data:

networks:
  pgnetwork:
    driver: bridge