server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: booking
          uri: lb://booking-service
          predicates:
            - Path=/booking/**
          filters:
            - StripPrefix=1

        - id: notification
          uri: lb://notification-service
          predicates:
            - Path=/notification/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/